version: '3'
services:
  fakeargocd:
    build:
      context: ./fake_dependencies/argocd
    ports:
      - "50900:3000"
  kafka:
    image: spotify/kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
    - "9090:9000"
    environment:
    - "ZK_HOSTS=kafka:2181"
